### ISSUE TITLE
Uncaught ReferenceError: Raven is not defined 

### ISSUE THREAD

**Issue by davidmaitland** [damiencaselli/ember-cli-sentry#1]
After running `ember install:addon ember-cli-sentry` and configuring the sentry ENV variables I get:

```
Uncaught ReferenceError: Raven is not defined
```

Is there anything else I need to install, if so which packages?

This is using ember version 1.9.1 and ember-cli version 0.1.12.

**Comment by davidmaitland** [comment]
Raven isn't a dependency of the plugin for some reason.

But if anyone else is having this problem you can put [raven.js](https://github.com/getsentry/raven-js) in your `vendor` directory and import it using `app.import('vendor/raven.js');` in your `Brocfile.js`.

**Comment by damiencaselli** [comment]
Hi David, actually there is no need for any dependency because the addon uses the `contentFor` hook to write the ravenjs script tag to the DOM (see [index file](https://github.com/damiencaselli/ember-cli-sentry/blob/master/index.js)).

To use it properly, you still need to add `/* global Raven */` to every file using Raven, or the linter it will constantly pester you with some Raven not defined error.

**Comment by davidmaitland** [comment]
Thanks for the update. Didn't see this before! Maybe something to put in the readme at some point :)
