### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by Turbo87** [damiencaselli/ember-cli-sentry#144]
@damiencaselli I would like to enable https://dependabot.com on this repository, but it seems that I don't have enough permissions to do that. Could you have a look at either enabling it or giving me enough permissions to do so myself? Thanks :)

**Comment by damiencaselli** [comment]
I've just enabled it :+1: 
I think permissions cannot be modified since it's a personal repository, but if you know a way to do it, please let me know.

**Comment by Turbo87** [comment]
awesome, thank you.

> I think permissions cannot be modified since it's a personal repository, but if you know a way to do it, please let me know.

yeah, that's what I expected unfortunately. we could move it to an org to make that easier if you're okay with that 🤔

**Comment by damiencaselli** [comment]
I'm totally fine with this, especially since I just stop by to janitor and I'm not really active on this project anymore (and with this account as well, but my e-alter ego @dashdashzako is a contributor). We already had this discussion a while ago and at that time it was simpler for everyone to keep the things as they were, but I wanted to make it an org to ease maintenance and collaboration.

Before making this move, can we make a complete list of what needs to be migrated so it goes as smoothly as possible?

**Comment by Turbo87** [comment]
> Before making this move, can we make a complete list of what needs to be migrated so it goes as smoothly as possible?

I think all we need to do is create the GitHub org, and then move this repo into it. After that `https://github.com/damiencaselli/ember-cli-sentry` should automatically forward to the new repo location unless you fork it again under that account.

I'm not aware of any other things that would need to be moved.

**Comment by damiencaselli** [comment]
@Turbo87 done :wink:

**Comment by Turbo87** [comment]
awesome, thank you 👍

**Comment by dschmidt** [comment]
Is there any interest to have `ember-cli-deploy-sentry`in the same organization? I'm not maintaining that well either.. and I'd be happy to hand it over

**Comment by Turbo87** [comment]
I can only speak for myself. I'm not using it so I can't maintain it, sorry :-/
