### ISSUE TITLE
Feedback wanted from Fastboot users

### ISSUE THREAD

**Issue by damiencaselli** [damiencaselli/ember-cli-sentry#60]
Hi, ember-cli-sentry users,

Does some of you have feedback to share about using this add-on with Fastboot? How the two work together? Have you noticed any weird behavior?

**Comment by damiencaselli** [comment]
Related to #59

**Comment by sevab** [comment]
Raven obviously doesn't work in node throwing the expected `Error while processing route: index XMLHttpRequest is not defined ReferenceError: XMLHttpRequest is not defined`

I have a use case where I report 404 routes via `captureMessage`, so considering using [`raven-node` for that](https://github.com/getsentry/raven-node).

If this addon wants to be Fastboot compatible, would be nice and should be quite easy to add this functionality by conditionally importing `raven-node` when in Fastboot environment and call `captureMessage`, `captureException` via `raven-node` instead of `raven.js`.

Users could opt-out from reporting in fastboot mode by setting, say, `fastboot: false` flag in `config/environment.js`.

**Comment by arschmitz** [comment]
Funny timing i just added sentry to my ember app running fastboot and ran into the same thing would be great if this used `raven-node` when in fastboot.

**Comment by tchak** [comment]
I opened a new PR #66 to use `raven-node` in fastboot
