### ISSUE TITLE
Update Sentry docs

### ISSUE THREAD

**Issue by Turbo87** [damiencaselli/ember-cli-sentry#61]
There are some [docs](https://docs.sentry.io/clients/javascript/integrations/ember/) on the Sentry page that describe how to use Sentry with Ember.js but the instructions are partly outdated and wrong. As this seems to be the recommended addon to use Sentry with Ember it would probably make sense to update that page mentioning the addon and fixing the other stuff.

The code of the docs page seems to be available at https://github.com/getsentry/raven-js/blob/master/docs/integrations/ember.rst

**Comment by damiencaselli** [comment]
@Turbo87 I've lost context of this and that (we're doing JS after all).

> it would probably make sense to update that page mentioning the addon and fixing the other stuff.

_that page_ refers to the one you linked, right? Or is it a page in the `ember-cli-sentry` repository?

**Comment by Turbo87** [comment]
yeah, it's the one I linked. I know the issue is technically in the wrong repo but I figured since we're more focused on Ember and they don't necessarily work with Ember that much we might be better suited to update that page. looking at the history of that page it seems that it was actually adopted from the Angular version, which is only partly compatible at this point.

**Comment by damiencaselli** [comment]
I see. Unfortunately the Ember add-on provided by Sentry isn't much integrat(ed|able) to the `ember-cli` toolchain, which makes it difficult to use in a recent Ember environment.

A year ago I sent this –unanswered– email to @mattrobenolt:

> Hi Matt,
> 
> I'm Damien, the guy maintaining the ember-cli-sentry plugin.
> 
> As Robert Jackson said in a pull request (https://github.com/damiencaselli/ember-cli-sentry/pull/10), we could kinda merge our codebases to make the Ember+Raven experience even better.
> That makes perfect sense to me, since the addon I created is merely an ember'd version of your work.
> 
> I'd gladly help making the tool even better.
> 
> Let me know what you think about it,
> 
> 
> Damien

This `ember-cli-sentry` add-on pretty much evolved in its own way, but I'm still very open to making the experience even better by making it even closer to Sentry.

That being said, I think the page you linked should simply mention a _deprecated_ warning. But if one wants to add a mention to this `ember-cli-sentry` add-on, they will get a free hug.

**Comment by mattrobenolt** [comment]
I'm probably bad at email. I also personally know nothing about Ember, so this is super foreign to me.

/cc @benvinegar

**Comment by Turbo87** [comment]
@mattrobenolt Ember is usually used with Ember CLI these days, which includes some sort of build pipeline and plugin architecture. `ember-cli-sentry` integrates your `raven-js` project into that build pipeline and automatically sets up a few things to make it very easy to get started.

Since Ember CLI is the recommended way to use Ember I'd propose to make this addon the recommended way to use Sentry in Ember too. The path described on the page I linked above is somewhat uncommon in Ember these days and probably complicating adoption.

**Comment by benvinegar** [comment]
I'd be glad to update it – the docs were just based on me opening up Ember and getting a working example going, not necessarily reflecting community best practices.

**Comment by damiencaselli** [comment]
Hi, I'm the 2-months-late-guy.

@Turbo87 can you please describe what you would improve in the Ravenjs doc?

@benvinegar From my perspective, the current docs are pretty much fine. The only missing info would be a mention about how to properly integrate with Ember: switching environments using config, and logging in dev mode. But I also think the Raven plugin is just a convenient way of making it available to anyone, and its purpose isn't to explain how to develop their own Ember apps. If Raven team was to explain every JS framework integration in-depth, that would be a huge time sink for you.

This add-on was created because of this kind of _owww f*** I logged prod to dev again_ and __ issues. Which aren't really issues if you think twice before typing code but, well, I usually don't 😄 
I tried to stick to the _Ember way_ of doing things: installing and configuring the add-on is rather straightforward, but can still be tailored to suit one's needs.

If you feel like this add-on is worth mentioning, then it may be worth to mention its existence in the integration doc. Concerning its legitimacy, I have no idea how widely it is used beside looking at its [npm stats](https://npm-stat.com/charts.html?package=ember-cli-sentry&from=2015-02-01&to=2016-12-13).

**Comment by Turbo87** [comment]
I think what I wrote in https://github.com/damiencaselli/ember-cli-sentry/issues/61#issuecomment-252899300 still holds true and is what I would recommend.
